basePath: /
definitions:
  domain.Booking:
    properties:
      booking_date:
        type: string
      created_at:
        type: string
      hours:
        type: integer
      id:
        type: integer
      status:
        type: string
      transport_id:
        type: integer
      user_id:
        type: integer
    type: object
  domain.Transport:
    properties:
      capacity:
        type: integer
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price_per_hour:
        type: number
    type: object
host: localhost:8081
info:
  contact: {}
  description: Water transport booking service
  title: Booking Service API
  version: "1.0"
paths:
  /bookings:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Booking'
            type: array
      summary: Get all bookings
      tags:
      - bookings
    post:
      consumes:
      - application/json
      parameters:
      - description: Booking
        in: body
        name: booking
        required: true
        schema:
          $ref: '#/definitions/domain.Booking'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
      summary: Create booking
      tags:
      - bookings
  /bookings/{id}/approve:
    patch:
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Approve booking
      tags:
      - bookings
  /bookings/{id}/reject:
    patch:
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Reject booking
      tags:
      - bookings
  /transports:
    get:
      description: Get list of transports
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Transport'
            type: array
      summary: Get all transports
      tags:
      - transports
    post:
      consumes:
      - application/json
      description: Create new water transport
      parameters:
      - description: Transport
        in: body
        name: transport
        required: true
        schema:
          $ref: '#/definitions/domain.Transport'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create transport
      tags:
      - transports
swagger: "2.0"
